name: build

on:
  push:
    branches:
      - master

jobs:
  build-api:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: [ '1.19.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go build .
      - name: Dir
        run: dir
      - name: Ls
        run: ls
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: D:\a\Houki\ #
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

